name = "hono-blog"
main = "src/index.ts"
compatibility_date = "2023-12-01"


[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "blog-api"
database_id = "d1826c5b-43db-4e4e-b1e1-98681795dde1"